OFException: Do not show <??+offset>.
The offset is useless if the symbol is unknown, especially if it gets
large because the offset is relative to 0.