OFException: Reduce backtrace size to 16
More than 16 is almost never useful, and 32 means it does no longer fit
on a 80x24 screen - or on the screen on a Nintendo 3DS or Wii.